spring:
  profiles:
    active: prod
  application:
    name: HOTELMANAGEMENTSYSTEM

## Server Configuration ##
server:
  servlet:
    context-path: /api/v1
  port: 8080

## Configuring info endpoint
info:
  app:
    name: Hotel Management System
    version: 1.0.0


## JWT Configuration ##
jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration: 36000000