spring:
  datasource:
    url: jdbc:mysql:localhost:3306/hotel_management_system
    username: root
    password: Zayar2142000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update